### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by stevebanik** [jasny/audio#2]
s/wavefrom/waveform/g

**Comment by jhaanji035** [comment]
Hi , I am facing small issue , Can you pls help me out 

<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'soxi command failed. 'soxi' is not
 recognized as an internal or external command,
operable program or batch file.' in C:\xampp\htdocs\audio-master\src\Jasny\Audio\Track.php:330
Stack trace:
#0 C:\xampp\htdocs\audio-master\src\Jasny\Audio\Track.php(281): Jasny\Audio\Track::exec('soxi', Array
)
#1 C:\xampp\htdocs\audio-master\src\Jasny\Audio\Track.php(140): Jasny\Audio\Track-&gt;soxi('-D')
#2 C:\xampp\htdocs\audio-master\src\Jasny\Audio\Track.php(185): Jasny\Audio\Track-&gt;getStat('length'
, '-D', 'float')
#3 C:\xampp\htdocs\audio-master\src\Jasny\Audio\Waveform.php(110): Jasny\Audio\Track-&gt;getLength()

#4 C:\xampp\htdocs\audio-master\src\Jasny\Audio\Waveform.php(200): Jasny\Audio\Waveform-&gt;calc()
#5 C:\xampp\htdocs\audio-master\src\Jasny\Audio\Waveform.php(305): Jasny\Audio\Waveform-&gt;getLength
()
#6 C:\xampp\htdocs\audio-master\src\Jasny\Audio\Waveform.php(282): Jasny\Audio\Waveform-&gt;outputJson
()
#7 C:\xampp\htdocs\audio-master\demo\waveform.php(12): Jasny\Audio\Waveform-&gt;o in <b>C:\xampp\htdocs
\audio-master\src\Jasny\Audio\Track.php</b> on line <b>330</b><br />

**Comment by jasny** [comment]
You need to set the path to [`sox`](http://sox.sourceforge.net/sox.html), [`soxi`](http://sox.sourceforge.net/soxi.html) and [`ffmeg`/`avconv`](https://libav.org/avconv.html).

https://github.com/jasny/audio/blob/master/src/Jasny/Audio/Track.php#L13

Note that I'm not 100% sure sox and/or ffmeg/avconv run on Windows.
