### ISSUE TITLE
Comparing two audio files.

### ISSUE THREAD

**Issue by ermiri** [jasny/audio#4]
Hi,
I search on google and find this library.Anyway all i need is to compare two sounds if they are identical or not.
Here is my problem:Let's say i have a sound X.From X i crop from 30 to 90 second,so create another file Y(which is X(30,90)).Again i crop another part from X from 35 to 90 second,so create another file Z(which is X(35,95)).
I need a script(php) to tell me that Y and Z are the same but Z is shefted with 5 seconds.

This is where your library would help me if it will produce the wave in a json file or something else.
Thanks.

**Comment by jasny** [comment]
Please ask your question on [Stackoverflow](http://www.stackoverflow.com). This issue tracker is for issues only.
